### ISSUE TITLE
Win10 Compiling Issues

### ISSUE THREAD

**Issue by GradiusX** [mwrlabs/KernelFuzzer#1]
ISSUE 1: Running "bughunt_build_x64_release.bat" on win10 does not work, or at least I couldn't make it to work. For example, vcvarsall.bat complains, as seen below, and also compiling with cl.exe throws several link errors

![1](https://cloud.githubusercontent.com/assets/10713510/17716590/43ada3a0-6401-11e6-9ad5-e1ab04cd4484.png)

FIX 1: Installing VS2015 and changing "Microsoft Visual Studio 12.0" to "Microsoft Visual Studio 14.0" makes it progress much further.

ISSUE 2: When compiling we're now met with the error below. get_time_in_ms which is found in brush.h is not implemented.

![2](https://cloud.githubusercontent.com/assets/10713510/17716752/f4a107e2-6401-11e6-8792-362da04eade6.png)

FIX 2: We could remove the line, comment, implement the function or set it to something fixed

After that everything worked perfectly .. very interesting fuzzer .. thanks :)

**Comment by NerdKernel2** [comment]
Hi @GradiusX,

Thanks for pointing those out! I have added the get_time_in_ms() function and edited the README to point out that you should change the build script to the VS you are using.

I also fixed the issue you pointed out on Twitter :).

**Comment by GradiusX** [comment]
Welcome :) and keep up the good work
