### ISSUE TITLE
Missing the bughunt_subprocess.c file

### ISSUE THREAD

**Issue by zenhumany** [mwrlabs/KernelFuzzer#2]
the bughunt_build_x86_release.bat need the bughunt_subprocess.c to compile,but didn't find this file?

**Comment by NerdKernel2** [comment]
Hey @zenhumany,

Thanks for noting that - the x86 build script was an old version that I didn't test (oops!). I have pushed a new script that should build a 32bit exe.

**Comment by zenhumany** [comment]
Hey @NerdKernel2 ,Thanks very much.
